import AppKit
import os

/// Polls NSPasteboard for changes and records new entries in ClipboardStore.
@MainActor
final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    private let logger = Logger(
        subsystem: "com.unstablemind.tamagotchai",
        category: "clipboard"
    )

    private var timer: Timer?
    private var lastChangeCount: Int

    /// Set to true briefly when we ourselves write to the pasteboard
    /// so we don't capture our own paste-back operations.
    var skipNextChange = false

    /// Pasteboard types that indicate sensitive or ephemeral content
    /// (password managers, text expanders, auto-generated content).
    /// See http://nspasteboard.org for the specification.
    private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType"),
        NSPasteboard.PasteboardType("com.typeit4me.clipping"),
    ]

    private init() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard timer == nil else { return }
        logger.info("Clipboard monitor started")
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.checkPasteboard()
            }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        logger.info("Clipboard monitor stopped")
    }

    private func checkPasteboard() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        if skipNextChange {
            skipNextChange = false
            return
        }

        // Skip concealed/transient content (passwords, text expanders, etc.)
        let types = Set(pb.types ?? [])
        if !types.isDisjoint(with: ignoredTypes) {
            logger.debug("Skipping concealed/transient clipboard content")
            return
        }

        // Capture which app owns the clipboard
        let sourceApp = NSWorkspace.shared.frontmostApplication
        let appName = sourceApp?.localizedName
        let appBundle = sourceApp?.bundleIdentifier

        // Try text first
        if let text = pb.string(forType: .string), !text.isEmpty {
            let entry = ClipboardEntry(
                id: UUID(),
                timestamp: Date(),
                contentType: .text,
                textContent: text,
                imageData: nil,
                fileURL: nil,
                sourceAppName: appName,
                sourceAppBundle: appBundle
            )
            ClipboardStore.shared.add(entry)
            return
        }

        // Try file URL
        if let urls = pb.readObjects(forClasses: [NSURL.self]) as? [URL],
           let url = urls.first
        {
            let entry = ClipboardEntry(
                id: UUID(),
                timestamp: Date(),
                contentType: .fileURL,
                textContent: nil,
                imageData: nil,
                fileURL: url.path,
                sourceAppName: appName,
                sourceAppBundle: appBundle
            )
            ClipboardStore.shared.add(entry)
            return
        }

        // Try image
        if let tiffData = pb.data(forType: .tiff),
           let image = NSImage(data: tiffData),
           let pngData = image.tiffRepresentation.flatMap({
               NSBitmapImageRep(data: $0)?.representation(using: .png, properties: [:])
           })
        {
            // Only store images up to 500KB to avoid bloating the store
            guard pngData.count <= 500_000 else {
                logger.info("Skipping large image (\(pngData.count) bytes)")
                return
            }
            let entry = ClipboardEntry(
                id: UUID(),
                timestamp: Date(),
                contentType: .image,
                textContent: nil,
                imageData: pngData,
                fileURL: nil,
                sourceAppName: appName,
                sourceAppBundle: appBundle
            )
            ClipboardStore.shared.add(entry)
        }
    }
}
